name: Actualizar Capturas Automáticas

on:
  schedule:
    # Corre a las 00:00 del día 1 de cada 3 meses (Enero, Abril, Julio, Octubre)
    - cron: '0 0 1 1,4,7,10 *'
  workflow_dispatch: # Esto activa un botón en GitHub para correrlo manualmente

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          pip install selenium webdriver-manager

      - name: Correr Script de Captura
        run: python capturar.py

      - name: Commit y Push de las imágenes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Imagenes/*.jpg
          git commit -m "Auto: Actualización de capturas de pantalla" || echo "Sin cambios"
          git push